<?php

declare(strict_types=1);

namespace Tests\Feature\Production;

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Schema;
use Tests\TestCase;

/**
 * Verifies migrations use Laravel schema builder patterns compatible with MySQL 8.x.
 * Does not require a live MySQL connection.
 */
final class MysqlMigrationCompatibilityTest extends TestCase
{
  use RefreshDatabase;

  private const LOOKUP_INDEX = 'errs_event_type_restored_idx';

  /** @var list<string> */
  private const REQUIRED_TABLES = [
    'communication_settings',
    'communication_routes',
    'communication_templates',
    'communication_email_logs',
    'communication_idempotency_keys',
    'lms_program_modules',
    'lms_courses',
    'lms_schools',
    'lms_school_orders',
    'lms_course_orders',
    'lms_school_enrollments',
  ];

  public function test_required_lms_and_communications_tables_exist_after_migrate(): void
  {
    foreach (self::REQUIRED_TABLES as $table) {
      $this->assertTrue(
        Schema::hasTable($table),
        "Expected table [{$table}] after migrations.",
      );
    }
  }

  public function test_lms_courses_has_program_module_foreign_key_column(): void
  {
    $this->assertTrue(Schema::hasColumn('lms_courses', 'program_module_id'));
  }

  public function test_migration_files_avoid_sqlite_only_raw_sql(): void
  {
    $files = File::glob(database_path('migrations/*.php')) ?: [];
    $this->assertNotEmpty($files);

    $violations = [];
    foreach ($files as $file) {
      $contents = File::get($file);
      $basename = basename($file);

      if (preg_match('/DB::statement\s*\(\s*[\'"]\s*(CREATE|ALTER|DROP)/i', $contents)) {
        $violations[] = "{$basename}: raw DDL via DB::statement";
      }

      if (str_contains($contents, 'AUTOINCREMENT') && ! str_contains($contents, 'sqlite')) {
        $violations[] = "{$basename}: SQLite AUTOINCREMENT syntax outside guarded block";
      }
    }

    $this->assertSame([], $violations, 'Migration compatibility issues: '.implode('; ', $violations));
  }

  public function test_event_registration_reset_snapshot_identifiers_fit_mysql_limit(): void
  {
    $autoGenerated = 'event_registration_reset_snapshots_event_id_reset_type_restored_at_index';
    $explicit = self::LOOKUP_INDEX;

    $this->assertSame(72, strlen($autoGenerated));
    $this->assertGreaterThan(64, strlen($autoGenerated));
    $this->assertLessThanOrEqual(64, strlen($explicit));

    $path = database_path('migrations/2026_10_01_120000_create_event_registration_reset_snapshots.php');
    $contents = File::get($path);
    $this->assertStringContainsString($explicit, $contents);
    $this->assertDoesNotMatchRegularExpression(
      '/\$table->index\(\s*\[\s*[\'"]event_id[\'"]\s*,\s*[\'"]reset_type[\'"]\s*,\s*[\'"]restored_at[\'"]\s*\]\s*\)/',
      $contents,
    );
    $this->assertStringNotContainsString('DROP TABLE', strtoupper($contents));
    $this->assertStringNotContainsString('Schema::drop(', $contents);

    $this->assertTrue(Schema::hasTable('event_registration_reset_snapshots'));
    $this->assertTrue(Schema::hasIndex('event_registration_reset_snapshots', $explicit));

    foreach (Schema::getIndexes('event_registration_reset_snapshots') as $index) {
      $name = (string) ($index['name'] ?? '');
      $this->assertLessThanOrEqual(
        64,
        strlen($name),
        "Index [{$name}] exceeds MySQL's 64-character identifier limit.",
      );
    }

    foreach ([
      'event_registration_reset_snapshots_uuid_unique',
      'event_registration_reset_snapshots_event_id_foreign',
      'event_registration_reset_snapshots_actor_id_foreign',
      'event_registration_reset_snapshots_restored_by_user_id_foreign',
    ] as $identifier) {
      $this->assertLessThanOrEqual(
        64,
        strlen($identifier),
        "Identifier [{$identifier}] exceeds MySQL's 64-character identifier limit.",
      );
    }
  }

  public function test_reset_snapshot_migration_creates_missing_table_with_short_index(): void
  {
    Schema::disableForeignKeyConstraints();
    Schema::dropIfExists('event_registration_reset_snapshots');
    Schema::enableForeignKeyConstraints();

    $this->assertFalse(Schema::hasTable('event_registration_reset_snapshots'));

    $this->resetSnapshotMigration()->up();

    $this->assertTrue(Schema::hasTable('event_registration_reset_snapshots'));
    $this->assertTrue(Schema::hasIndex('event_registration_reset_snapshots', self::LOOKUP_INDEX));
    $this->assertSame(1, $this->namedIndexCount('event_registration_reset_snapshots', self::LOOKUP_INDEX));
  }

  public function test_reset_snapshot_migration_adds_short_index_when_table_exists_without_it(): void
  {
    Schema::table('event_registration_reset_snapshots', function (Blueprint $table): void {
      $table->dropIndex(self::LOOKUP_INDEX);
    });

    $this->assertFalse(Schema::hasIndex('event_registration_reset_snapshots', self::LOOKUP_INDEX));

    $this->resetSnapshotMigration()->up();

    $this->assertTrue(Schema::hasIndex('event_registration_reset_snapshots', self::LOOKUP_INDEX));
    $this->assertSame(1, $this->namedIndexCount('event_registration_reset_snapshots', self::LOOKUP_INDEX));
  }

  public function test_reset_snapshot_migration_does_not_duplicate_existing_short_index(): void
  {
    $this->assertTrue(Schema::hasIndex('event_registration_reset_snapshots', self::LOOKUP_INDEX));

    $this->resetSnapshotMigration()->up();

    $this->assertTrue(Schema::hasIndex('event_registration_reset_snapshots', self::LOOKUP_INDEX));
    $this->assertSame(1, $this->namedIndexCount('event_registration_reset_snapshots', self::LOOKUP_INDEX));
  }

  private function resetSnapshotMigration(): Migration
  {
    /** @var Migration $migration */
    $migration = require database_path('migrations/2026_10_01_120000_create_event_registration_reset_snapshots.php');

    return $migration;
  }

  private function namedIndexCount(string $table, string $name): int
  {
    return collect(Schema::getIndexes($table))
      ->filter(fn (array $index): bool => ($index['name'] ?? '') === $name)
      ->count();
  }
}
