<?php

declare(strict_types=1);

namespace App\Providers;

use App\Models\IamAuditLog;
use App\Models\Member;
use App\Models\MemberInterview;
use App\Models\Permission;
use App\Models\Role;
use App\Models\User;
use App\Modules\Cms\Models\CmsCatalogItem;
use App\Modules\Cms\Models\CmsCountry;
use App\Modules\Cms\Models\CmsFormSubmission;
use App\Modules\Cms\Models\CmsLeadershipProfile;
use App\Modules\Cms\Models\CmsMedia;
use App\Modules\Cms\Models\CmsMediaFolder;
use App\Modules\Cms\Models\CmsMinistry;
use App\Modules\Cms\Models\CmsMenu;
use App\Modules\Cms\Models\CmsPage;
use App\Modules\Cms\Models\CmsPageSection;
use App\Modules\Cms\Models\CmsPartner;
use App\Modules\Cms\Models\CmsSeo;
use App\Modules\Cms\Models\CmsSetting;
use App\Modules\Cms\Models\CmsTestimonial;
use App\Modules\Cms\Policies\CmsCatalogItemPolicy;
use App\Modules\Cms\Policies\CmsCountryPolicy;
use App\Modules\Cms\Policies\CmsFormSubmissionPolicy;
use App\Modules\Cms\Policies\CmsLeadershipProfilePolicy;
use App\Modules\Cms\Policies\CmsMediaFolderPolicy;
use App\Modules\Cms\Policies\CmsMediaPolicy;
use App\Modules\Cms\Policies\CmsMenuPolicy;
use App\Modules\Cms\Policies\CmsMinistryPolicy;
use App\Modules\Cms\Policies\CmsPagePolicy;
use App\Modules\Cms\Policies\CmsPageSectionPolicy;
use App\Modules\Cms\Policies\CmsPartnerPolicy;
use App\Modules\Cms\Policies\CmsSeoPolicy;
use App\Modules\Cms\Policies\CmsSettingPolicy;
use App\Modules\Cms\Policies\CmsTestimonialPolicy;
use App\Modules\Donations\Models\Donation;
use App\Modules\Donations\Policies\DonationPolicy;
use App\Modules\Events\Models\Event;
use App\Modules\Events\Models\EventCategory;
use App\Modules\Events\Models\EventCertificateTemplate;
use App\Modules\Events\Models\EventCoupon;
use App\Modules\Events\Models\EventExportJob;
use App\Modules\Events\Models\EventNotificationTemplate;
use App\Modules\Events\Models\EventRegistration;
use App\Modules\Events\Models\EventRegistrationPayment;
use App\Modules\Events\Models\EventReportSnapshot;
use App\Modules\Events\Models\EventVolunteerAssignment;
use App\Modules\Events\Models\EventVolunteerRole;
use App\Modules\Events\Models\Speaker;
use App\Modules\Events\Models\Venue;
use App\Modules\Events\Policies\EventCategoryPolicy;
use App\Modules\Events\Policies\EventCertificateTemplatePolicy;
use App\Modules\Events\Policies\EventCouponPolicy;
use App\Modules\Events\Policies\EventExportJobPolicy;
use App\Modules\Events\Policies\EventNotificationTemplatePolicy;
use App\Modules\Events\Policies\EventPolicy;
use App\Modules\Events\Policies\EventRegistrationPaymentPolicy;
use App\Modules\Events\Policies\EventRegistrationPolicy;
use App\Modules\Events\Policies\EventReportSnapshotPolicy;
use App\Modules\Events\Policies\EventVolunteerAssignmentPolicy;
use App\Modules\Events\Policies\EventVolunteerRolePolicy;
use App\Modules\Events\Policies\SpeakerPolicy;
use App\Modules\Events\Policies\VenuePolicy;
use App\Modules\Counselling\Models\CounsellingCase;
use App\Modules\Counselling\Policies\CounsellingCasePolicy;
use App\Modules\Lms\Models\Assessment;
use App\Modules\Lms\Models\CertificateTemplate;
use App\Modules\Lms\Models\Course;
use App\Modules\Lms\Models\CourseCategory;
use App\Modules\Lms\Models\CourseCertificate;
use App\Modules\Lms\Models\CourseOrder;
use App\Modules\Lms\Models\Enrollment;
use App\Modules\Lms\Models\Instructor;
use App\Modules\Lms\Models\Question;
use App\Modules\Lms\Policies\AssessmentPolicy;
use App\Modules\Lms\Policies\CourseCategoryPolicy;
use App\Modules\Lms\Policies\CourseCertificatePolicy;
use App\Modules\Lms\Policies\CourseOrderPolicy;
use App\Modules\Lms\Policies\CoursePolicy;
use App\Modules\Lms\Policies\EnrollmentPolicy;
use App\Modules\Lms\Policies\InstructorPolicy;
use App\Policies\IamAuditLogPolicy;
use App\Policies\MemberInterviewPolicy;
use App\Policies\MemberPolicy;
use App\Policies\PermissionPolicy;
use App\Policies\RolePolicy;
use App\Policies\UserPolicy;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\ServiceProvider;

final class AuthServiceProvider extends ServiceProvider
{
  public function boot(): void
  {
    Gate::policy(User::class, UserPolicy::class);
    Gate::policy(Member::class, MemberPolicy::class);
    Gate::policy(MemberInterview::class, MemberInterviewPolicy::class);
    Gate::policy(Role::class, RolePolicy::class);
    Gate::policy(Permission::class, PermissionPolicy::class);
    Gate::policy(IamAuditLog::class, IamAuditLogPolicy::class);
    Gate::policy(CmsCountry::class, CmsCountryPolicy::class);
    Gate::policy(CmsSetting::class, CmsSettingPolicy::class);
    Gate::policy(CmsPage::class, CmsPagePolicy::class);
    Gate::policy(CmsPageSection::class, CmsPageSectionPolicy::class);
    Gate::policy(CmsFormSubmission::class, CmsFormSubmissionPolicy::class);
    Gate::policy(CmsLeadershipProfile::class, CmsLeadershipProfilePolicy::class);
    Gate::policy(CmsMinistry::class, CmsMinistryPolicy::class);
    Gate::policy(CmsPartner::class, CmsPartnerPolicy::class);
    Gate::policy(CmsTestimonial::class, CmsTestimonialPolicy::class);
    Gate::policy(CmsMenu::class, CmsMenuPolicy::class);
    Gate::policy(CmsSeo::class, CmsSeoPolicy::class);
    Gate::policy(CmsCatalogItem::class, CmsCatalogItemPolicy::class);
    Gate::policy(CmsMedia::class, CmsMediaPolicy::class);
    Gate::policy(CmsMediaFolder::class, CmsMediaFolderPolicy::class);
    Gate::policy(Donation::class, DonationPolicy::class);
    Gate::policy(Event::class, EventPolicy::class);
    Gate::policy(Venue::class, VenuePolicy::class);
    Gate::policy(Speaker::class, SpeakerPolicy::class);
    Gate::policy(EventCategory::class, EventCategoryPolicy::class);
    Gate::policy(EventRegistration::class, EventRegistrationPolicy::class);
    Gate::policy(EventReportSnapshot::class, EventReportSnapshotPolicy::class);
    Gate::policy(EventExportJob::class, EventExportJobPolicy::class);
    Gate::policy(EventNotificationTemplate::class, EventNotificationTemplatePolicy::class);
    Gate::policy(EventCertificateTemplate::class, EventCertificateTemplatePolicy::class);
    Gate::policy(EventVolunteerRole::class, EventVolunteerRolePolicy::class);
    Gate::policy(EventVolunteerAssignment::class, EventVolunteerAssignmentPolicy::class);
    Gate::policy(EventCoupon::class, EventCouponPolicy::class);
    Gate::policy(EventRegistrationPayment::class, EventRegistrationPaymentPolicy::class);
    Gate::policy(CounsellingCase::class, CounsellingCasePolicy::class);
    Gate::policy(Course::class, CoursePolicy::class);
    Gate::policy(CourseCategory::class, CourseCategoryPolicy::class);
    Gate::policy(Instructor::class, InstructorPolicy::class);
    Gate::policy(Enrollment::class, EnrollmentPolicy::class);
    Gate::policy(Assessment::class, AssessmentPolicy::class);
    Gate::policy(Question::class, AssessmentPolicy::class);
    Gate::policy(CourseCertificate::class, CourseCertificatePolicy::class);
    Gate::policy(CertificateTemplate::class, CourseCertificatePolicy::class);
    Gate::policy(CourseOrder::class, CourseOrderPolicy::class);

    Gate::define('permission', function (User $user, string $permission): bool {
      return $user->hasPermission($permission);
    });
  }
}
